apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-64c5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-64c5@sha256:75d39f1c5a06005bacd068b5229859a80dd76d1f892fc7f71d40b203ff1b2f28
        name: my-nodejs
        resources: {}
status: {}
